
const StockTypes = {
    GET_ALL_WAREHOUSE_PRODUCTS_STOCK: 'GET_ALL_WAREHOUSE_PRODUCTS_STOCK',
    UPDATE_PRODUCT_PRICE: 'UPDATE_PRODUCT_PRICE',
    UPDATE_PRODUCT_STOCK: 'UPDATE_PRODUCT_STOCK',
    REMOVE_PRODUCT_FROM_WAREHOUSE: 'REMOVE_PRODUCT_FROM_WAREHOUSE'
}

export default StockTypes;